### ISSUE TITLE
支持1.20.6

### ISSUE THREAD

**Issue by addpromax** [MrXiaoM/DeathMessages#4]
[10:47:42] [Server thread/INFO]: [DeathMessages] PlaceholderAPI Hook Enabled!
[10:47:42] [Server thread/INFO]: [DeathMessages] PlugMan found. Adding this plugin to its ignored plugins list due to WorldGuard hook being enabled!
[10:47:42] [Server thread/ERROR]: Error occurred while enabling DeathMessages v1.4.17 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at DeathMessages-1.4.17.jar/dev.mrshawn.deathmessages.DeathMessages.serverVersion(DeathMessages.java:69) ~[DeathMessages-1.4.17.jar:?]
	at DeathMessages-1.4.17.jar/dev.mrshawn.deathmessages.DeathMessages.majorVersion(DeathMessages.java:73) ~[DeathMessages-1.4.17.jar:?]
	at DeathMessages-1.4.17.jar/dev.mrshawn.deathmessages.DeathMessages.checkGameRules(DeathMessages.java:191) ~[DeathMessages-1.4.17.jar:?]
	at DeathMessages-1.4.17.jar/dev.mrshawn.deathmessages.DeathMessages.onEnable(DeathMessages.java:60) ~[DeathMessages-1.4.17.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.20.6.jar:git-Purpur-2197]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.6.jar:git-Purpur-2197]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.6.jar:git-Purpur-2197]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:565) ~[purpur-1.20.6.jar:git-Purpur-2197]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:685) ~[purpur-1.20.6.jar:git-Purpur-2197]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:444) ~[purpur-1.20.6.jar:git-Purpur-2197]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:358) ~[purpur-1.20.6.jar:git-Purpur-2197]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1154) ~[purpur-1.20.6.jar:git-Purpur-2197]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[purpur-1.20.6.jar:git-Purpur-2197]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[10:47:42] [Server thread/INFO]: [DeathMessages] Disabling DeathMessages v1.4.17

**Comment by MrXiaoM** [comment]
获取版本的时候出错了，我换了获取方式，再试试

**Comment by addpromax** [comment]
10:22:00] [Server thread/ERROR]: Error occurred while enabling DeathMessages v1.4.17 (Is it up to date?)
java.lang.NumberFormatException: For input string: "craftbukkit"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.base/java.lang.Integer.parseInt(Integer.java:662) ~[?:?]
	at java.base/java.lang.Integer.parseInt(Integer.java:778) ~[?:?]
	at DeathMessages-1.4.17.jar/dev.mrshawn.deathmessages.DeathMessages.majorVersion(DeathMessages.java:74) ~[DeathMessages-1.4.17.jar:?]
	at DeathMessages-1.4.17.jar/dev.mrshawn.deathmessages.DeathMessages.checkGameRules(DeathMessages.java:192) ~[DeathMessages-1.4.17.jar:?]
	at DeathMessages-1.4.17.jar/dev.mrshawn.deathmessages.DeathMessages.onEnable(DeathMessages.java:60) ~[DeathMessages-1.4.17.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:618) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:567) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:357) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1150) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[10:22:00] [Server thread/INFO]: [DeathMessages] Disabling DeathMessages v1.4.17

**Comment by addpromax** [comment]
已支持 并且也支持1.21
